/**
 * Adjective + noun word lists used by the deterministic-probe nickname
 * assignment algorithm (see `assign.ts`). Both lists are EXACTLY 256
 * entries (a power of 2) so a single byte from the seed-derived hash
 * picks an index with zero modulo bias.
 *
 * Curation rules (Pre-Mainnet 5.0.10 plan):
 *   - All entries lowercase, alphabetic only (no digits, no hyphens,
 *     no spaces).
 *   - No pejorative adjectives: nothing that could insult the holder
 *     (`craven`, `pathetic`, `lazy`, `weak`, …).
 *   - No negative-trait nouns: no `loser`, `failure`, `idiot`, …
 *   - No first names (the user's "Mikey + Baby" suggestion was
 *     rejected for this reason — handle-style names like
 *     `brave-otter` read as a handle, not as a real person being
 *     impersonated).
 *   - Word combinations should never insult the holder. The whole
 *     Cartesian product gets a manual snapshot review at PR time and
 *     is then frozen.
 *
 * Sources: hand-curated from public-domain word fields used by
 * Docker's `moby-friendly-name`, Heroku's haikunator, and GitHub's
 * repo-name suggester (all permissive forks). Vendored as inline
 * arrays rather than depending on `unique-names-generator` to keep
 * the bundle tight + the curation visible in code review.
 *
 * Algorithm version: bumping either list (or the algorithm itself)
 * MUST bump `NICKNAME_ALGORITHM_VERSION` in `db.ts`. Mixing versions
 * in the same DB is forbidden — the boot invariant in `index.ts`
 * fails fast if it sees rows from a different version.
 */

export const ADJECTIVES: readonly string[] = [
  "agile",
  "alert",
  "amber",
  "ancient",
  "arctic",
  "aurora",
  "autumn",
  "azure",
  "bashful",
  "beaming",
  "blazing",
  "blissful",
  "bold",
  "boundless",
  "brave",
  "breezy",
  "bright",
  "brilliant",
  "brisk",
  "bronze",
  "bubbly",
  "calm",
  "candid",
  "ceramic",
  "cerulean",
  "charming",
  "cheerful",
  "cherry",
  "chestnut",
  "chipper",
  "chrome",
  "classic",
  "clean",
  "clear",
  "clever",
  "cobalt",
  "coral",
  "cosmic",
  "cozy",
  "crimson",
  "crisp",
  "crystal",
  "curious",
  "cyan",
  "daring",
  "dazzling",
  "dewy",
  "distant",
  "divine",
  "dreamy",
  "eager",
  "earnest",
  "ebony",
  "ecstatic",
  "elated",
  "electric",
  "elegant",
  "emerald",
  "enchanted",
  "energetic",
  "ethereal",
  "evening",
  "faithful",
  "fancy",
  "fiery",
  "fleeting",
  "flowing",
  "fluffy",
  "foggy",
  "fond",
  "forest",
  "fragrant",
  "fresh",
  "friendly",
  "frosty",
  "fuzzy",
  "gallant",
  "gentle",
  "ginger",
  "glassy",
  "gleaming",
  "glimmering",
  "glittering",
  "glossy",
  "glowing",
  "golden",
  "graceful",
  "grand",
  "granite",
  "grateful",
  "green",
  "happy",
  "hardy",
  "hazel",
  "hearty",
  "heavenly",
  "helpful",
  "hidden",
  "honest",
  "humble",
  "icy",
  "indigo",
  "infinite",
  "inky",
  "ivory",
  "jade",
  "jolly",
  "jovial",
  "joyful",
  "jumbo",
  "keen",
  "kind",
  "kindly",
  "lavish",
  "lemon",
  "lilac",
  "limber",
  "little",
  "lively",
  "lone",
  "lucky",
  "lunar",
  "luscious",
  "lustrous",
  "magenta",
  "magical",
  "maple",
  "marbled",
  "maroon",
  "marvelous",
  "mauve",
  "melodic",
  "merry",
  "mighty",
  "mindful",
  "minty",
  "misty",
  "modest",
  "moonlit",
  "mossy",
  "muted",
  "mystic",
  "neon",
  "nimble",
  "noble",
  "northern",
  "olive",
  "opal",
  "orange",
  "ornate",
  "painted",
  "pastel",
  "peaceful",
  "peachy",
  "pearly",
  "peppy",
  "perky",
  "pewter",
  "placid",
  "plucky",
  "plum",
  "plush",
  "polished",
  "primrose",
  "pristine",
  "proud",
  "pure",
  "purple",
  "quaint",
  "quartz",
  "quiet",
  "quirky",
  "radiant",
  "rapid",
  "ready",
  "regal",
  "resilient",
  "rosy",
  "royal",
  "ruby",
  "rugged",
  "rustic",
  "sable",
  "saffron",
  "sage",
  "sapphire",
  "savory",
  "scarlet",
  "seafoam",
  "serene",
  "shimmering",
  "shining",
  "silken",
  "silver",
  "simple",
  "sincere",
  "sleek",
  "smiling",
  "snowy",
  "solar",
  "solemn",
  "southern",
  "sparkling",
  "spicy",
  "spirited",
  "splendid",
  "spotted",
  "sprightly",
  "spry",
  "starlit",
  "starry",
  "steady",
  "steel",
  "sterling",
  "still",
  "striped",
  "stunning",
  "sturdy",
  "summer",
  "sunny",
  "sunset",
  "sweet",
  "swift",
  "tame",
  "tangerine",
  "tawny",
  "teal",
  "tender",
  "terrific",
  "thankful",
  "thoughtful",
  "thriving",
  "tidy",
  "timeless",
  "tiny",
  "topaz",
  "tranquil",
  "tropical",
  "true",
  "trusty",
  "twilight",
  "valiant",
  "velvet",
  "verdant",
  "vivid",
  "warm",
  "watchful",
  "wavy",
  "whimsical",
  "winged",
  "wise",
  "woodland",
  "woven",
  "young",
  "zealous",
  "zesty",
];

export const NOUNS: readonly string[] = [
  "acorn",
  "almond",
  "anchor",
  "antler",
  "apple",
  "apricot",
  "arrow",
  "ash",
  "aspen",
  "badger",
  "bamboo",
  "banner",
  "basil",
  "beacon",
  "beaver",
  "beech",
  "beetle",
  "berry",
  "bison",
  "blossom",
  "bluebell",
  "bobcat",
  "boulder",
  "breeze",
  "brook",
  "butterfly",
  "cactus",
  "camellia",
  "canary",
  "candle",
  "canopy",
  "canyon",
  "cardinal",
  "cavern",
  "cedar",
  "chalet",
  "chestnut",
  "cinder",
  "cinnamon",
  "citrus",
  "clay",
  "clover",
  "cloud",
  "comet",
  "compass",
  "copper",
  "coral",
  "cosmos",
  "cottage",
  "cotton",
  "cougar",
  "cove",
  "crab",
  "crag",
  "crane",
  "cricket",
  "crystal",
  "cypress",
  "daffodil",
  "daisy",
  "dawn",
  "deer",
  "delta",
  "desert",
  "dewdrop",
  "diamond",
  "dolphin",
  "dove",
  "dragonfly",
  "dune",
  "dusk",
  "eagle",
  "ember",
  "emerald",
  "falcon",
  "fawn",
  "fern",
  "finch",
  "firefly",
  "flame",
  "flamingo",
  "fleece",
  "flint",
  "foal",
  "forest",
  "fountain",
  "fox",
  "frond",
  "galaxy",
  "garden",
  "geode",
  "geyser",
  "glacier",
  "glade",
  "gleam",
  "glen",
  "grove",
  "gull",
  "harbor",
  "hare",
  "harvest",
  "haven",
  "hawk",
  "heather",
  "hedge",
  "heron",
  "hickory",
  "hilltop",
  "hollow",
  "honey",
  "horizon",
  "hummingbird",
  "ibis",
  "iceberg",
  "iris",
  "island",
  "ivy",
  "jasmine",
  "jay",
  "juniper",
  "kestrel",
  "kite",
  "koi",
  "lagoon",
  "lakeshore",
  "lantern",
  "lark",
  "laurel",
  "lavender",
  "leaf",
  "lemur",
  "leopard",
  "lichen",
  "lighthouse",
  "lily",
  "linden",
  "lion",
  "lotus",
  "lupine",
  "lynx",
  "magnolia",
  "mallow",
  "manatee",
  "mango",
  "maple",
  "marble",
  "marigold",
  "marlin",
  "marmot",
  "marsh",
  "meadow",
  "meteor",
  "mirage",
  "monarch",
  "moonbeam",
  "morning",
  "moss",
  "mountain",
  "mulberry",
  "nebula",
  "nectar",
  "nightingale",
  "oak",
  "ocean",
  "olive",
  "opal",
  "orchard",
  "orchid",
  "otter",
  "owl",
  "palace",
  "palm",
  "panda",
  "pansy",
  "papaya",
  "pavilion",
  "peacock",
  "pearl",
  "pebble",
  "petal",
  "phoenix",
  "pine",
  "pinecone",
  "planet",
  "platinum",
  "pollen",
  "pond",
  "poppy",
  "prairie",
  "puma",
  "quail",
  "quartz",
  "quasar",
  "quill",
  "quokka",
  "raccoon",
  "rainbow",
  "raindrop",
  "raven",
  "reef",
  "ridge",
  "river",
  "robin",
  "rose",
  "rosemary",
  "rune",
  "salmon",
  "sandstone",
  "sapling",
  "sapphire",
  "savanna",
  "seagull",
  "sequoia",
  "shoreline",
  "silhouette",
  "sky",
  "snail",
  "sparrow",
  "spiral",
  "spring",
  "squirrel",
  "starfish",
  "stone",
  "stork",
  "stream",
  "summit",
  "sunbeam",
  "sunflower",
  "swallow",
  "swan",
  "sycamore",
  "terrace",
  "thicket",
  "thistle",
  "thunder",
  "tiger",
  "tortoise",
  "trail",
  "treetop",
  "tundra",
  "turquoise",
  "valley",
  "vine",
  "violet",
  "walnut",
  "waterfall",
  "wave",
  "willow",
  "windmill",
  "wisteria",
  "wolf",
  "woodland",
  "wren",
  "yarrow",
  "zenith",
  "zephyr",
];

/**
 * Banned-word backstop. The curated lists above already exclude
 * pejoratives — this set is the load-bearing runtime check enforced at
 * module load (in dev) and inside the test suite. Any future word-list
 * edit that slips a banned token in will fail the test before it can
 * land. List drawn from common-sense filters; keep small + targeted.
 */
const BANNED = new Set<string>([
  // Pejorative adjectives
  "lazy",
  "weak",
  "ugly",
  "stupid",
  "craven",
  "pathetic",
  "worthless",
  "sad",
  "angry",
  "boring",
  "dumb",
  "rude",
  "mean",
  "evil",
  "wicked",
  "cruel",
  "vile",
  "nasty",
  "cursed",
  "doomed",
  "broken",
  // Negative-trait nouns
  "loser",
  "failure",
  "idiot",
  "fool",
  "moron",
  "coward",
  "victim",
  "wreck",
  "garbage",
  "trash",
  "scum",
  "vermin",
  "parasite",
]);

/**
 * Module-load assertions. Turns the schema invariants (length,
 * alphabetic-only, no banned words, no duplicates) into hard runtime
 * errors so a bad list never reaches production. Cheap enough to run
 * unconditionally — both lists together are 512 entries.
 */
// Module-scope so the validator doesn't recompile the pattern on every
// list entry (biome's `useTopLevelRegex` rule).
const ALPHABETIC_LOWERCASE_RE = /^[a-z]+$/;

function validateList(list: readonly string[], label: string): void {
  if (list.length !== 256) {
    throw new Error(
      `nicknames/words.ts: ${label} must have exactly 256 entries, has ${list.length}`
    );
  }
  const seen = new Set<string>();
  for (const word of list) {
    if (!ALPHABETIC_LOWERCASE_RE.test(word)) {
      throw new Error(
        `nicknames/words.ts: ${label} entry "${word}" must be lowercase a-z only`
      );
    }
    if (BANNED.has(word)) {
      throw new Error(
        `nicknames/words.ts: ${label} entry "${word}" is in the banned-words set`
      );
    }
    if (seen.has(word)) {
      throw new Error(
        `nicknames/words.ts: ${label} entry "${word}" is duplicated`
      );
    }
    seen.add(word);
  }
}

validateList(ADJECTIVES, "ADJECTIVES");
validateList(NOUNS, "NOUNS");

/**
 * Banned-words exposed for the snapshot test that walks the full
 * Cartesian product. Tests assert no `${adj}-${noun}` combination
 * contains a banned token as a substring (catches things like
 * `lazy-otter` if `lazy` ever sneaks back in).
 */
export const BANNED_WORDS: ReadonlySet<string> = BANNED;
